cabal-version:       3.0
build-type:          Simple

name:                tsftl-lab-llmlmm
version:             0.1.0.0
stability:           experimental
category:            Data
synopsis:            Low-level (i.e., representation polymorphic) manual/linear memory management

author:              thesnakefromthelemma
maintainer:          rafayaashary01@gmail.com
license:             BSD-3-Clause
license-file:        ../LICENSE

extra-doc-files:     README.md

source-repository    head
    type:            git
    location:        https://github.com/thesnakefromthelemma/tsftl-lab/llmlmm


-- * Common

common                   common

    build-depends:       base >= 4.21 && < 4.23

    default-language:    Haskell2010

    ghc-options:         -Wall
                         -O2
                         -fexpose-all-unfoldings
                         -fspecialize-aggressively
                         -ddump-to-file
                         -ddump-simpl
                         -dno-typeable-binds
                         -dsuppress-idinfo
                         -dsuppress-module-prefixes

common                   exe

    ghc-options:         -fllvm
                         -optlo-passes=default<O3>
                         -optlc-O3
                         -optlc-mcpu=native


-- * Library

Flag                    debug
    Description:        Record calls to primops to stderr
    Default:            False
    Manual:             True

library

    import:             common

    build-depends:      template-haskell >= 2.23 && < 2.25

    hs-source-dirs:     src

    c-sources:          src/Data/AddrPrimOps.cmm

    if flag(debug)
        cpp-options:    -DDEBUG=1
    else
        cpp-options:    -DDEBUG=0

    exposed-modules:    Data.RuntimeRep
                        Prelude.Linear
                        Data.State
                        Data.State.Linear
                        Data.Addr
                        Data.Addr.Linear
    
    other-modules:      Prelude.Linear.TH
                        Data.Addr.TH
                        Data.Addr.Linear.TH


-- * Tests

test-suite             test

    import:            common
          ,            exe

    build-depends:     tsftl-lab-llmlmm

    hs-source-dirs:    test

    main-is:           Main.hs

    type:              exitcode-stdio-1.0

    other-modules:     Ramanujan

    ghc-options:       -fllvm
                       -optlo-passes=default<O3>
                       -optlc-O3
                       -optlc-mcpu=native



-- * Benchmarks

test-suite             bench

    import:            common
          ,            exe

    build-depends:     tsftl-lab-llmlmm

    hs-source-dirs:    bench

    main-is:           Main.hs

    type:              exitcode-stdio-1.0