cabal-version:       3.0
build-type:          Simple

name:                llmlmm
version:             0.1.0.0
stability:           experimental
category:            Data
synopsis:            Low-level (i.e., representation polymorphic) manual/linear (i.e., non-GC) memory management

author:              thesnakefromthelemma
maintainer:          rafayaashary01@gmail.com
license:             BSD-3-Clause
license-file:        ../LICENSE

extra-doc-files:     README.md

source-repository    head
    type:            git
    location:        https://github.com/thesnakefromthelemma/tsftl-lab/llmlmm


-- * Flags

-- | It's currently necessary to switch this off in the repl
Flag                simd
    Description:    Compile functions involving SIMD intrinsics
    Default:        True
    Manual:         False

-- | Generally results in better-optimized asm if configured
Flag                llvm
    Description:    Compile with llvm backend
    Default:        False
    Manual:         True

-- | Currently lengthens compilation by 3-6x
Flag                full
    Description:    Compile all of 'Urlike'
    Default:        True
    Manual:         False

-- | Log calls to non-GC heap primops to stderr
Flag                debug
    Description:    Log calls to non-GC heap primops to stderr
    Default:        False
    Manual:         True


-- * Common

common                   common

    build-depends:       base >= 4.21 && < 4.23

    default-language:    Haskell2010

    if flag(simd)
        cpp-options:     -DSIMD=1
    else
        cpp-options:     -DSIMD=0

    if flag(full)
        cpp-options:     -DFULL=1
    else
        cpp-options:     -DFULL=0

    ghc-options:         -Wall
                         -O2
                         -fexpose-all-unfoldings
                         -fspecialize-aggressively
                         -ddump-to-file
                         -ddump-simpl
                         -dno-typeable-binds
                         -dsuppress-idinfo
                         -dsuppress-module-prefixes
    
    if flag(llvm)
        ghc-options:     -fllvm
                         -optlo-passes=default<O3>
                         -optlc-O3
                         -optlc-mcpu=native


-- * Library

library

    import:             common

    build-depends:      template-haskell >= 2.23 && < 2.25

    hs-source-dirs:     src

    if flag(debug)
        c-sources:      src/Data/Addr/Debug.c

    -- | Unfortunately cabal isn't yet able
    -- to see that this should be recompiled
    -- when the value of 'debug' changes, so
    -- the user will have to run @cabal clean@
    -- or some equivalent
    cmm-sources:        src/Data/State/PrimOps.cmm
                        src/Data/Addr/PrimOps.cmm

    -- | @-DDEBUG=1@ does nothing...
    -- perhaps worth documenting
    if flag(debug)
        cmm-options:    -optCmmP-DDAPOS=1
    else
        cmm-options:    -optCmmP-DDAPOS=0

    exposed-modules:    Data.RuntimeRep
                        Prelude.Linear
                        Data.State
                        Data.State.Linear
                        Data.State.Linear.Unsafe
                        Data.Addr
                        Data.Addr.Unsafe
                        Data.Addr.Linear
                        Data.Addr.Linear.Unsafe
    
    other-modules:      Misc.TH
                        Prelude.Linear.TH
                        Data.State.Linear.TH
                        Data.Addr.TH
                        Data.Addr.Linear.TH


-- * Tests

test-suite             llmlmm-test

    import:            common

    build-depends:     llmlmm

    hs-source-dirs:    test

    main-is:           Main.hs

    type:              exitcode-stdio-1.0


-- * Benchmarks

test-suite             llmlmm-bench

    import:            common

    build-depends:     llmlmm

    hs-source-dirs:    bench

    main-is:           Main.hs

    type:              exitcode-stdio-1.0


-- * Ramanujan

executable             ramanujan

    import:            common

    build-depends:     llmlmm

    hs-source-dirs:    ramanujan

    main-is:           Main.hs